Add database
ardivad2015/java-filmorate pull request #4
Opened 2024-10-01 01:43 UTC by ardivad2015

2024-10-01 08:16 UTC, mikita95 requested changes
Все сделано просто отлично :) Оставил лишь пару рекомендаций

2024-10-01 08:16 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/db/LikeDBStorage.java
> +                SIMPLE_INSERT_QUERY,
При добавлении лайков можно было бы выполнять операцию merge, иначе сейчас при повторной вставке произойдет ошибка

2024-10-01 08:16 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/memory/InMemoryFilmRatingStorage.java
> +       /*
Можно было бы оформить в виде java doc

2024-10-01 09:14 UTC, ardivad2015 commented on src/main/java/ru/yandex/practicum/filmorate/dao/memory/InMemoryFilmRatingStorage.java
> +       /*
Вставил сюда, чтобы копировать названия. Забыл удалить потом.

2024-10-02 07:39 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-10-08 07:38 UTC, merged